#!/bin/bash
shopt -s nullglob
# shellcheck disable=SC1091
source "$HOME/.local/share/banager/deps/checks.sh"
# Custom Aliases
# You put your custom aliases below this
external() {
    # shellcheck disable=SC1091
    source -- "$(blesh-share)"/ble.sh --attach=none
    # Uncomment which everone you want to use and have installed
    # eval "$(thefuck --alias -l SHELL_LOGGER)"
    # eval "$(pay-respects bash)"
    eval "$(starship init bash)"
    # TODO: Make a check and have it in the template nixos config for starship and zoxide working
    if ! command -v nix &>/dev/null; then 
        eval "$(zoxide init --cmd "cd" bash)"
    fi
}
