#!/bin/bash
prune="$XDG_CONFIG_HOME/banager/user/prune.sh"
if [ -z "$prune" ]; then
    touch "$prune"
    bash_declare="#!/bin/bash"
    bash_gen="# this is a file generated by the $HOME/.bashrc file"
    dont_delete="# do not delete this file, it is needed for " # info: make sure to have the function, call, and/or file that needs the variable (plus line #) after the variable is used
    echo "Would you like to prune in days or size? "
    read -r prune_choice
    case "$prune_choice" in
        *ay* | *AY*) 
            prune_denotion="--day"
            echo "How many days? "
            read -r days_choice
            chosen_prune="$days_choice"
            ;;
        *ize* | *IZE*) 
            prune_denotion="--size"
            echo "Size amount? "
            read -r size_choice
            echo "Byte size? (In all caps and using the acronym, example: GB) "
            read -r byte_choice
            chosen_prune="$size_choice$byte_choice"
    esac
    echo -e "$bash_declare\n$bash_gen\n$dont_delete\npruning=\"$prune_denotion\"\nprune=$chosen_prune" >> "${XDG_CONFIG_HOME:-$HOME/.config}"
fi
source "$HOME"/.config/banager/user/prune.sh
if command -v &>/dev/null; then
    if [ -z "${XDG_DATA_HOME:-$HOME/.local/Trash}" ]; then
        gtrash prune "$pruning $prune"
    fi
fi
