#!/bin/bash
nix_user="$XDG_CONFIG_HOME/bash/user/nixos.sh"
if command -v nix &>/dev/null; then 
    if [ ! -e "$nix_user" ]; then 
        touch "$XDG_CONFIG_HOME/bash/user/nixos.sh"
        bash_declare="#!/bin/bash"
        bash_gen="# this is a file generated by the $HOME/.bashrc file"
        dont_delete="# do not delete this file, it is needed for " # info: make sure to have the function, call, and/or file that needs the variable (plus line #) after the variable is used
        echo "Nix Path [can use environment variables] (default: /etc/nixos/): "
        read -r nix_path 
        case "$nix_path" in 
            "default" | "Default" | "") 
                # We have this to set a default path for users
                nix_path="/etc/nixos" 
                ;;
        esac
        echo -e "$bash_declare\n$bash_gen\n$dont_delete\nexport NIX_PATH=$nix_path" >> "$nix_user"
    fi
    use_nixld() {
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$NIX_LD_LIBRARY_PATH"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$NIX_LD_LIBRARY_PATH/pkgconfig"
    }
    # shellcheck disable=SC1090
    source "$nix_user"
    # NIXOS ALIASES
    # shellcheck disable=SC2153
    alias nixos-rebuild='cd $NIX_PATH && $SUPER nixos-rebuild'
    alias nix-store='$SUPER nix-store'
    alias nix-collect-garbage='$SUPER nix-collect-garbage'
    alias nix-add='cd $HOME/nixos && nvim'
fi
