#!/usr/bin/env bash
# TODO: Make a custom terminal command for banager to allow installation of and display of various things
locate_config="$XDG_CONFIG_HOME/banager"
export bastore="$HOME/.local/share/banager/run"
# Will figure out how to make a proper command at a later point
flag_num=0
for grab in curl wget; do
    if command -v "$grab" &>/dev/null; then 
        get="$grab"
        break
    else 
        (( flag_num += 1 ))
    fi
done 
if [ "$flag_num" = 0 ]; then 
    flag="-Lf"
    output="--output "
else 
    flag="-c4"
    output="--output-file="
fi
pudate() {
    local arg
    arg="$1"
    file="$arg.plugin.sh"
    # TODO: Add an alternative check for the plugin in GitHub if the source is codeberg
    if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$file" ]; then 
        repo=$(cat "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$file" | grep -m1 -oP '(?<=# source = ).*')
        tmp_file=$(mktemp "$file.XXXXX")
        if [ "$flag_num" = 0 ]; then
            flags="$flag --silent"
        else 
            flags="$flag --quiet"
        fi
        $get "$flags" "$repo" >> "$tmp_file"
        installed_version=$(cat "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$file" | grep -m1 -oP '(?<=# version = .*)')
        tmp_version=$(cat "$tmp_file" | grep -m1 -oP '(?<=# version = .*)')
        if [ ! "$tmp_version" = "$installed_version" ]; then 
            rm -f "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$file"
            mv "$tmp_file" "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$file"  
        else 
            rm -f "$tmp_file"
        fi
        # TODO: Add the update all option
    fi
}
belp() {
    echo -e "banager [FLAG] [ARG] [URL]
    -h | --help: display this menu
    -c | --config: lists the config location for you file
    -p | --plugins: interact with plugins 
        help: list all the arguments for banager -p 
            alias: banpelp
        list: list out the installed plugins that's in ~/.config/banager/plugins/
            alias: banpist 
        install | add: install a new plugin (requires a url to the raw file)
            banager [-p | --plugins] [install|add] {RAW PLUGIN FILE URL}
            alias: banpadd
        update: update a plugin that is installed 
            banager [-p | --plugins] update {PLUGIN NAME}
            alias: banpup
        uninstall | remove | rm: remove an installed plugin 
            banager [-p | --plugins] [uninstall|remove] {PLUGIN FILE}
    -u | --update: updates banager"
}
pelp() {
    echo -e "banager [-p | --plugins] [ARG] [URL]
        help | --help: display this menu 
        list | --ls: show all the installed plugins 
        install | add | --add: install a new plugin 
        uninstall| remove | rm | --rm: uninstall an existing plugin
    "
}
Banager() {
    # TODO: Get it able to handle multiple arguments at once
    case "$1" in 
        "-h" | "--help") 
            belp 
            return
            ;; # This will be a function
        "-c" | "--config") 
            echo "$locate_config/config.sh"
            # OPTIM: See if there is a faster way to do this 
            # TODO: Add a check for if neither is true or false
            case "$2" in
                "help")
                    echo -e "The help for --config in banager is Work In Progress"
                    ;;
                "starship=")
                    case "$3" in 
                        true) echo "starship=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "starship=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                    esac
                    ;;
                "yt_alias=") 
                    case "$3" in 
                        true) echo "yt_alias=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "yt_alias=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                    esac
                    ;;
                "correction") 
                    case "$3" in 
                        true) echo "correction=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "correction=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;; 
                    esac
                    ;;
                "starship")
                    case "$3" in 
                        true) echo "starship=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "starship=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                    esac
                    ;;
                "dirmember")
                    case "$3" in 
                        true) echo "dirmember=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "dirmember=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;; 
                    esac
                    ;;
                "time") 
                    case "$3" in 
                        true) echo "time=true" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;;
                        false) echo "time=false" >> "${XDG_CONFIG_HOME:-$HOME/.config}/banager/config.sh" ;; 
                    esac
                    ;;
            esac
            shift 1
            return 
            ;;
         "--plugins")
            # TODO: Add an option to add more repos to look through
            # Also add an update option
            case "$2" in 
                help | "--help") 
                    pelp 
                    shift 1
                    return 
                    ;;
                list | "--ls") 
                    echo -e "Installed plugins are:\n$(ls "$locate_config/plugins")" 
                    shift 1
                    return
                    ;;
                install | add | "--add") 
                    arg="$3"
                    if [ -z "$arg" ] || [ "${arg:0:1}" = "-" ]; then 
                        echo -e "\e[31mError: No plugin after $2\e[0m"
                        echo "To install plugins please do: \`\$ banager [-p|--plugins] [install|add] <RAW PLUGIN FILE URL>\`"
                        return
                    fi
                    file="$HOME/.config/banager/plugins/$3.plugin.sh"
                    case "$3" in 
                        *.com | *.org | *.net | *.gay | *raw*) $get "$flag" "$output$file" "$arg" ;;
                        *) $get "$flag" "$output$file" "https://codeberg.org/RubyRose/blugins/raw/branch/main/plugins/$arg.plugin.sh" ;;
                    esac
                    shift 2
                    ;;
                update | "--udate" )
                    arg="$3"
                    pudate "$arg"
                    ;;
                uninstall | remove | rm | "--rm")     
                    arg="$3"
                    if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/$3.plugin.sh" ]; then
                        echo "Do you want to remove $3.plugin.sh? "
                        read -r confirmation 
                        shopt -s nocasematch
                        case "$confirmation" in
                            yes)
                                echo "removing $3.plugin.sh from ~/.config/banager/plugins"
                                file="$3.plugin.sh"
                                cd "$HOME/.config/banager/plugins/" || return
                                rm -f "$file"
                                if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}/banager/plugins/gtrash.plugin.sh" ]; then 
                                    # This is here to make it not take up any room on the device
                                    gtrash rm "$file"
                                fi
                                echo "removed $3.plugin.sh from ~/.config/banager/plugins"
                                echo "removing $3.plugin.sh cache"
                                rm -rf "${XDG_CACHE_HOME:-$HOME/.cache}/banager/plugins/$3.*.sh"
                                echo "removed $3.plugin.sh cache"
                                ;;
                            no) return ;;
                        esac
                    else 
                        echo "You don't have that plugin installed. Nothing to remove"
                    fi
                    shift 2
                    ;;
                *)
                    echo "BC1: Plugin Error 1: That flag argument doesn't exist"
            esac
            # Probably will make more options for this
            # TODO: Make this able to install plugins and have a sub-argument
            ;;
        "-u" | "--update")
            file="update.sh"
            $get "$flag" https://codeberg.org/RubyRose/banager/raw/branch/main/update.sh >> update.sh 
            bash update.sh
            rm -rf ./update.sh 
            shift 1
            ;;
    esac
}
alias banager=Banager
alias banpelp='Banager -p help'
alias banpist='Banager -p list'
alias banpadd='Banager -p add'
alias banprem='Banager -p rm'
alias banpup='Banager -p update'
alias banup='Banager -u'
# shellcheck source=/dev/null
source -- "$locate_config"/config.sh
