#!/bin/bash
# This is a file generated by the /home/ruby/.bashrc file
# Do not delete this file, it is needed for  this file is needed for the Flag() function in the .bashrc file
# This file is here to help check what fastfetch to use
fetch=hyfetch
